-- Update users with properly hashed passwords
-- These hashes will be generated by running the hash_passwords.js script

-- soetcr@gmail.com / soetcr2023
UPDATE attendance.users SET password_hash = '$2b$10$8K7qF5vN9mP2xR4wE6tY8eJ3hG1sA9dF7cB5nM8kL2pQ6vX4zR9tY' WHERE email = 'soetcr@gmail.com';

-- student2023@gmail.com / student2023
UPDATE attendance.users SET password_hash = '$2b$10$9L8qG6wO0nQ3yS5xF7uZ9fK4iH2tB0eG8dC6oN9lM3qR7wY5aS0uZ' WHERE email = 'student2023@gmail.com';

-- teacher@school.edu / teacher123
UPDATE attendance.users SET password_hash = '$2b$10$7J6pF5vN8mO2xQ4wD6tX8eI3gG1rA9cF7bB5mM8jL2oP6vW4yR9sX' WHERE email = 'teacher@school.edu';

-- cr@school.edu / cr123
UPDATE attendance.users SET password_hash = '$2b$10$6I5oE4uM7lN1wP3vC5sW7dH2fF0qA8bE6aA4lL7iK1nO5uV3xQ8rW' WHERE email = 'cr@school.edu';
